# Generated by Django 5.2.17 on 2026-09-22 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64)),
                ('counts', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('scope', models.JSONField(default=dict)),
                ('mode', models.CharField(default='recognition', editable=False, max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('context', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='scholars.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='current_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scholars.questionrevision'),
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('choices', models.JSONField()),
                ('selected', models.PositiveSmallIntegerField(null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('answered_at', models.DateTimeField(null=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.questionrevision')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scholars.practicesession')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.category')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subject_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('payload', models.JSONField()),
                ('study_content', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.category')),
                ('subcategories', models.ManyToManyField(to='scholars.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.topic'),
        ),
        migrations.CreateModel(
            name='TopicRedirect',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.topic')),
            ],
        ),
        migrations.AddConstraint(
            model_name='practicesession',
            constraint=models.UniqueConstraint(fields=('user', 'request_key'), name='unique_session_request'),
        ),
        migrations.AddConstraint(
            model_name='questionrevision',
            constraint=models.UniqueConstraint(fields=('question', 'digest'), name='unique_question_revision'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='unique_session_position'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'revision'), name='unique_session_question'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.CheckConstraint(condition=models.Q(('selected__isnull', True), models.Q(('selected__gte', 0), ('selected__lte', 3)), _connector='OR'), name='valid_choice_index'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('answered_at__isnull', True), ('is_correct__isnull', True), ('selected__isnull', True)), models.Q(('answered_at__isnull', False), ('is_correct__isnull', False), ('selected__isnull', False)), _connector='OR'), name='complete_answer_record'),
        ),
    ]
