# Generated by Django 5.2.17 on 2026-09-22 16:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='comparison_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='is_personal_best',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='scope_label',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='corrected_previous_miss',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RewardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_on', models.DateField()),
                ('points', models.PositiveSmallIntegerField()),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='scholars.sessionquestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'question', 'earned_on'), name='one_question_reward_per_day'), models.CheckConstraint(condition=models.Q(('points__in', [1, 2])), name='valid_participation_points')],
            },
        ),
        migrations.CreateModel(
            name='StudyPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_goal', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('weekly_goal__lte', 100)), name='weekly_goal_at_most_100')],
            },
        ),
        migrations.CreateModel(
            name='StudyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_opened_at', models.DateTimeField()),
                ('studied_at', models.DateTimeField(null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'topic'), name='unique_student_topic_state')],
            },
        ),
    ]
