# Generated by Django 5.2.17 on 2026-09-22 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0002_practicesession_comparison_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20)),
                ('successes', models.PositiveSmallIntegerField(default=0)),
                ('last_evidence_on', models.DateField()),
                ('due_on', models.DateField(db_index=True)),
                ('last_attempt_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='sessionquestion',
            name='complete_answer_record',
        ),
        migrations.AddField(
            model_name='practicesession',
            name='abandoned_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='selection',
            field=models.CharField(default='random', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='attempt_kind',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='revealed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='review_due_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='review_successes',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='self_assessment',
            field=models.BooleanField(null=True),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('answered_at__isnull', True), ('is_correct__isnull', True), ('selected__isnull', True), ('self_assessment__isnull', True)), models.Q(('answered_at__isnull', False), ('is_correct__isnull', False), ('selected__isnull', False), ('self_assessment__isnull', True)), models.Q(('answered_at__isnull', False), ('is_correct__isnull', True), ('revealed_at__isnull', False), ('selected__isnull', True), ('self_assessment__isnull', False)), _connector='OR'), name='complete_answer_record'),
        ),
        migrations.AddField(
            model_name='reviewstate',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.questionrevision'),
        ),
        migrations.AddField(
            model_name='reviewstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reviewstate',
            constraint=models.UniqueConstraint(fields=('user', 'revision', 'mode'), name='unique_review_evidence'),
        ),
    ]
