# Generated by Django 5.2.17 on 2026-09-24 12:49

import django.db.models.deletion
from django.db import migrations, models


def initialize_banks(apps, schema_editor):
    # Frozen v1 normalization; no dependency on future application algorithms.
    import hashlib
    import json
    import unicodedata
    Category = apps.get_model('scholars', 'Category')
    Question = apps.get_model('scholars', 'Question')
    AnswerBank = apps.get_model('scholars', 'AnswerBank')
    banks = {}
    for category, payload in Question.objects.filter(active=True, topic__active=True, current_revision__isnull=False).order_by('pk').values_list('topic__category_id', 'current_revision__payload'):
        bank = banks.setdefault(category, {})
        for answer in [payload['correct_answer'], *payload['distractors']]:
            key = ''.join(c for c in unicodedata.normalize('NFD', answer) if not unicodedata.category(c).startswith('M'))
            key = ' '.join(key.lower().translate(str.maketrans('’‘“”–—−', "''\"\"---")).split())
            bank.setdefault(key, answer.strip())
    for category in Category.objects.all():
        bank = banks.get(category.pk, {})
        answers = [bank[key] for key in sorted(bank)]
        version = hashlib.sha256(json.dumps(['typed-v1', category.pk, answers], sort_keys=True, ensure_ascii=False, separators=(',', ':')).encode()).hexdigest()
        AnswerBank.objects.get_or_create(pk=version, defaults=dict(category=category.pk, answers=answers))
        Category.objects.filter(pk=category.pk).update(typed_bank_id=version)


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0003_reviewstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerBank',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('answers', models.JSONField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='sessionquestion',
            name='complete_answer_record',
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='typed_answer',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='typed_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scholars.answerbank'),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='answer_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scholars.answerbank'),
        ),
        migrations.RunPython(initialize_banks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('answered_at__isnull', True), ('is_correct__isnull', True), ('selected__isnull', True), ('self_assessment__isnull', True), ('skipped', False), ('typed_answer__isnull', True)), models.Q(('answered_at__isnull', False), ('is_correct__isnull', False), ('selected__isnull', False), ('self_assessment__isnull', True), ('skipped', False), ('typed_answer__isnull', True)), models.Q(('answered_at__isnull', False), ('is_correct__isnull', True), ('revealed_at__isnull', False), ('selected__isnull', True), ('self_assessment__isnull', False), ('skipped', False), ('typed_answer__isnull', True)), models.Q(('answer_bank__isnull', False), ('answered_at__isnull', False), ('is_correct__isnull', False), ('selected__isnull', True), ('self_assessment__isnull', True), ('skipped', False), ('typed_answer__isnull', False), models.Q(('typed_answer', ''), _negated=True)), models.Q(('answer_bank__isnull', False), ('answered_at__isnull', False), ('is_correct', False), ('selected__isnull', True), ('self_assessment__isnull', True), ('skipped', True), ('typed_answer__isnull', True)), _connector='OR'), name='complete_answer_record'),
        ),
    ]
