# Generated by Django 5.2.17 on 2026-09-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0004_answerbank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='mode',
            field=models.CharField(default='typed', editable=False, max_length=20),
        ),
    ]
