# Generated by Django 5.2.17 on 2026-09-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0005_alter_practicesession_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='format',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('typed', 'Typed')], db_index=True, default='multiple_choice', max_length=20),
        ),
    ]
