# Generated by Django 5.2.17 on 2026-09-26 02:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0006_question_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studypreferences',
            name='categories',
            field=models.ManyToManyField(blank=True, to='scholars.category'),
        ),
        migrations.AddField(
            model_name='studypreferences',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('subcategory_label', models.CharField(max_length=500)),
                ('category_label', models.CharField(max_length=100)),
                ('phase', models.CharField(choices=[('reading', 'Reading'), ('quiz', 'Quiz'), ('review', 'Review'), ('passed', 'Passed'), ('abandoned', 'Abandoned')], default='reading', max_length=12)),
                ('version', models.PositiveIntegerField(default=0)),
                ('reading_position', models.PositiveSmallIntegerField(default=0)),
                ('review_topic_ids', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(null=True)),
                ('abandoned_at', models.DateTimeField(null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(null=True)),
                ('score', models.PositiveSmallIntegerField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='scholars.studysession')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='StudyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reading', 'Reading'), ('quiz', 'Quiz'), ('passed', 'Passed')], max_length=12)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='scholars.studysession')),
            ],
        ),
        migrations.CreateModel(
            name='StudySessionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('content', models.JSONField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='scholars.studysession')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.topic')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='StudyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.answerbank')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.questionrevision')),
                ('session_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scholars.studysessiontopic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='scholars.studysession')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_completions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('typed_answer', models.CharField(max_length=240, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(null=True)),
                ('answered_at', models.DateTimeField(null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='scholars.studyattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholars.studyquestion')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'position'), name='unique_study_answer_position'), models.UniqueConstraint(fields=('attempt', 'question'), name='unique_study_attempt_question'), models.CheckConstraint(condition=models.Q(models.Q(('answered_at__isnull', True), ('is_correct__isnull', True), ('skipped', False), ('typed_answer__isnull', True)), models.Q(('answered_at__isnull', False), ('is_correct__isnull', False), ('skipped', False), ('typed_answer__isnull', False), models.Q(('typed_answer', ''), _negated=True)), models.Q(('answered_at__isnull', False), ('is_correct', False), ('skipped', True), ('typed_answer__isnull', True)), _connector='OR'), name='complete_study_answer')],
            },
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(fields=('user', 'request_key'), name='unique_study_start'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(condition=models.Q(('phase__in', ['reading', 'quiz', 'review'])), fields=('user',), name='one_active_study_session'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('abandoned_at__isnull', True), ('completed_at__isnull', True), ('phase__in', ['reading', 'quiz', 'review'])), models.Q(('abandoned_at__isnull', True), ('completed_at__isnull', False), ('phase', 'passed')), models.Q(('abandoned_at__isnull', False), ('completed_at__isnull', True), ('phase', 'abandoned')), _connector='OR'), name='study_phase_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='studyattempt',
            constraint=models.UniqueConstraint(fields=('session', 'number'), name='unique_study_attempt'),
        ),
        migrations.AddConstraint(
            model_name='studyattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('score__isnull', True)), models.Q(('completed_at__isnull', False), ('score__isnull', False)), _connector='OR'), name='study_attempt_score_complete'),
        ),
        migrations.AddConstraint(
            model_name='studysessiontopic',
            constraint=models.UniqueConstraint(fields=('session', 'topic'), name='unique_study_topic'),
        ),
        migrations.AddConstraint(
            model_name='studysessiontopic',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='unique_study_topic_position'),
        ),
        migrations.AddConstraint(
            model_name='studyquestion',
            constraint=models.UniqueConstraint(fields=('session_topic', 'revision'), name='unique_study_pinned_question'),
        ),
        migrations.AddConstraint(
            model_name='topiccompletion',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='unique_topic_completion'),
        ),
    ]
