# Generated by Django 5.2.17 on 2026-09-26 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_imported_baselines(apps, schema_editor):
    Question = apps.get_model('scholars', 'Question')
    Question.objects.using(schema_editor.connection.alias).update(imported_revision_id=models.F('current_revision_id'))


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0007_studypreferences_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='edit_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='imported_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scholars.questionrevision'),
        ),
        migrations.AddField(
            model_name='question',
            name='origin',
            field=models.CharField(choices=[('imported', 'Imported'), ('teacher', 'Teacher-created')], default='imported', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='override_base_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scholars.questionrevision'),
        ),
        migrations.AddField(
            model_name='question',
            name='override_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scholars.questionrevision'),
        ),
        migrations.AddField(
            model_name='questionrevision',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(seed_imported_baselines, migrations.RunPython.noop),
    ]
