# Generated by Django 5.2.17 on 2026-09-27 00:46

import django.db.models.constraints
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0008_question_authoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('archived', models.BooleanField(default=False)),
                ('edit_version', models.PositiveIntegerField(default=0)),
                ('generation_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedQuizItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scholars.savedquiz')),
                ('reviewed_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.questionrevision')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('quiz', 'question'), name='unique_saved_quiz_question'), models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('quiz', 'position'), name='unique_saved_quiz_position'), models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='saved_quiz_position_positive')],
            },
        ),
    ]
