# Generated by Django 5.2.17 on 2026-09-27 01:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0009_saved_quizzes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('title', models.CharField(max_length=160)),
                ('phase', models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='waiting', max_length=12)),
                ('version', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('question_count', models.PositiveSmallIntegerField()),
                ('grading_version', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('ended_early', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholars.savedquiz')),
            ],
        ),
        migrations.CreateModel(
            name='LiveParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('roster_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_participations', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='scholars.livequiz')),
            ],
        ),
        migrations.CreateModel(
            name='LiveConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='scholars.livequiz')),
            ],
        ),
        migrations.CreateModel(
            name='LiveQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('topic_id_snapshot', models.CharField(max_length=100)),
                ('topic_title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('opened_at', models.DateTimeField(null=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('answer_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.answerbank')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scholars.livequiz')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholars.questionrevision')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='LiveResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('skipped', 'Skipped'), ('unanswered', 'Unanswered')], max_length=12)),
                ('typed_answer', models.CharField(blank=True, max_length=240)),
                ('finalized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='scholars.liveparticipant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='scholars.livequizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='LiveTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField()),
                ('action', models.CharField(max_length=12)),
                ('expected_version', models.PositiveIntegerField()),
                ('expected_position', models.PositiveSmallIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='scholars.livequiz')),
            ],
        ),
        migrations.AddConstraint(
            model_name='livequiz',
            constraint=models.UniqueConstraint(fields=('host', 'request_key'), name='unique_live_host_request'),
        ),
        migrations.AddConstraint(
            model_name='livequiz',
            constraint=models.UniqueConstraint(models.Value(1), condition=models.Q(('phase__in', ['waiting', 'running'])), name='one_open_live_quiz'),
        ),
        migrations.AddConstraint(
            model_name='liveparticipant',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='unique_live_participant'),
        ),
        migrations.AddIndex(
            model_name='liveconnection',
            index=models.Index(fields=['game', 'last_seen'], name='live_presence_lookup'),
        ),
        migrations.AddConstraint(
            model_name='livequizquestion',
            constraint=models.UniqueConstraint(fields=('game', 'position'), name='unique_live_question_position'),
        ),
        migrations.AddConstraint(
            model_name='liveresponse',
            constraint=models.UniqueConstraint(fields=('participant', 'question'), name='unique_live_response'),
        ),
        migrations.AddConstraint(
            model_name='livetransition',
            constraint=models.UniqueConstraint(fields=('game', 'request_key'), name='unique_live_transition'),
        ),
    ]
