# Generated by Django 5.2.17 on 2026-09-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0010_live_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='livequiz',
            name='roster_size_at_start',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
