# Generated by Django 5.2.17 on 2026-09-27 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_import_provenance(apps, schema_editor):
    """Retain the old pointer relationships as audit evidence before dropping them."""
    Question = apps.get_model('scholars', 'Question')
    Change = apps.get_model('scholars', 'QuestionChange')
    alias = schema_editor.connection.alias
    pending = []
    for q in Question.objects.using(alias).only('id', 'current_revision_id', 'imported_revision_id',
            'override_revision_id', 'override_base_revision_id', 'active', 'edit_version').iterator(chunk_size=500):
        pending.append(Change(question_id=q.pk, kind='database_ownership', before={
            'current_revision_id': q.current_revision_id, 'imported_revision_id': q.imported_revision_id,
            'override_revision_id': q.override_revision_id, 'override_base_revision_id': q.override_base_revision_id,
            'active': q.active, 'edit_version': q.edit_version}, after={
            'current_revision_id': q.current_revision_id, 'active': q.active, 'edit_version': q.edit_version}))
        if len(pending) == 500:
            Change.objects.using(alias).bulk_create(pending)
            pending = []
    Change.objects.using(alias).bulk_create(pending)


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0011_live_roster_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='questionchange',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionchange',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='scholars.question'),
        ),
        migrations.RunPython(preserve_import_provenance, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='question',
            name='imported_revision',
        ),
        migrations.RemoveField(
            model_name='question',
            name='override_base_revision',
        ),
        migrations.RemoveField(
            model_name='question',
            name='override_revision',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('', 'Not rated'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty__in', ['', 'easy', 'medium', 'hard'])), name='question_valid_difficulty'),
        ),
    ]
