# Generated by Django 5.2.17 on 2026-10-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0012_database_owned_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveparticipant',
            name='question_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='liveparticipant',
            name='timer_position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livequiz',
            name='late_joiners',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='livequiz',
            name='timed_scoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liveresponse',
            name='points',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
