# Generated by Django 5.2.17 on 2026-09-22 15:42

import django.core.validators
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryCredential',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('\\A[a-z0-9][a-z0-9_-]{2,31}\\Z', 'Use 3–32 lowercase letters, digits, underscores or hyphens.')])),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('session_version', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_admin', True)), fields=('is_admin',), name='one_administrator'), models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_username_casefold'), models.CheckConstraint(condition=models.Q(('is_admin', False), ('is_active', True), _connector='OR'), name='administrator_stays_active'), models.CheckConstraint(condition=models.Q(('username__regex', '^[a-z0-9][a-z0-9_-]{2,31}$')), name='username_format')],
            },
        ),
    ]
