"""Build a paginated local browser for full-run outputs and correction history."""
import argparse
from pathlib import Path

from typed_question_full import RUN

HTML = r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Typed questions · full generation</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f5f4f0;color:#202d2b;font:16px/1.6 system-ui,sans-serif}header,main,footer{max-width:1100px;margin:auto;padding:24px}header{padding-top:40px}h1{font-size:36px;line-height:1.2;margin:8px 0}h2{font-size:22px}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.1em;color:#557466;font-weight:700}.muted,.meta{font-size:13px;color:#66716c}.stats{display:flex;gap:28px;flex-wrap:wrap;margin:24px 0}.stats b{display:block;font-size:28px}.toolbar{display:flex;gap:12px;align-items:end;flex-wrap:wrap;background:white;border:1px solid #d8ddd6;border-radius:12px;padding:18px}label{display:flex;flex-direction:column;font-size:13px;gap:4px}input,select,button{font:inherit;padding:9px;border:1px solid #aab9ae;border-radius:6px;background:white;color:inherit}input{max-width:100%}button{cursor:pointer}button:disabled{opacity:.4;cursor:default}article{background:white;border:1px solid #d8ddd6;border-radius:12px;padding:24px;margin:16px 0}.question{font-size:21px;line-height:1.55}.answer{font-size:21px;font-weight:700;color:#22583e}details{padding:5px 0}summary{font-weight:600;cursor:pointer}.badge{font-size:12px;padding:4px 9px;border-radius:12px;background:#e5eee7}.remaining{background:#fff0d8;color:#794b10}.notes{background:#f8f8f5;padding:14px;margin-top:14px;border-radius:7px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}blockquote{margin:8px 0;border-left:3px solid #becdc2;padding:10px 15px}.pagination{display:flex;justify-content:space-between;align-items:center;gap:15px;margin:20px 0}.topic{color:#527064;font-size:14px}.hide-topics .topic{display:none}a{color:#22583e}main{padding-top:0}@media(max-width:600px){header,main,footer{padding:18px}h1{font-size:28px}article{padding:18px}.question{font-size:19px}}</style>
<header><div class="eyebrow">Huddleston Science · Full generation · GPT-6 Luna · xhigh</div><h1>Questions designed for typed answers</h1>
<p>Readable topic context, one specific answer per question, and an automatic review turn for possible giveaways.</p>
<div class="stats" id="stats">Loading run summary…</div>
<p class="muted" id="runStatus"></p>
<div class="toolbar"><label>Search<input id="search" type="search" placeholder="Topic, question, answer…"></label><label>Category<select id="category"><option value="">All categories</option></select></label><label>Correction status<select id="status"><option value="">All questions</option><option value="changed">Corrected</option><option value="reviewed">Sent for review</option><option value="remaining">Remaining detector flags</option><option value="untouched">No detector flag</option></select></label><button id="answers">Show answers</button><button id="topics">Hide topic labels</button></div>
<p id="count" class="muted" aria-live="polite"></p><div class="pagination"><button id="previous">Previous</button><span id="page" class="muted"></span><button id="next">Next</button></div>
<p class="muted">Flags are text-match signals, not proven errors. “No detector flag” is not a factual or ambiguity certification. Original multiple-choice data is preserved. <a href="typed-questions.json">Question JSON</a> · <a href="giveaway-review.json">Correction history</a> · <a href="remaining-flags.json">Remaining flags</a></p></header>
<main id="cards"></main><footer class="muted">Original and corrected stems are preserved. Corrections keep the same answers; unflagged questions are protected from changes.</footer>
<script>
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let questions=[],review=[],notes=new Map(),filtered=[],page=0,showAnswers=false;const size=40,contextCache=new Map();
function flagText(flags){return flags.map(f=>`<li><b>${esc(f.kind.replaceAll('_',' '))}:</b> “${esc(f.matched_text)}” matches “${esc(f.answer_text)}”</li>`).join('')}
function render(){const start=page*size;let chunk=filtered.slice(start,start+size);$('count').textContent=filtered.length+' questions match';$('page').textContent=filtered.length?`${start+1}–${Math.min(start+size,filtered.length)} of ${filtered.length}`:'No matches';$('previous').disabled=page===0;$('next').disabled=start+size>=filtered.length;
 $('cards').innerHTML=chunk.map(q=>{let n=notes.get(q.question_id),remaining=n?.flags_after?.length,changed=n?.changed;let badge=remaining?'Remaining detector flag':changed?'Corrected':n?'Reviewed; unchanged':'No detector flag';return `<article><div class="meta">${esc(q.category)} · Question ${q.slot}</div><div class="topic">${esc(q.topic)}</div><p class="question">${esc(q.question)}</p><details class="answerBox" ${showAnswers?'open':''}><summary>Answer</summary><p class="answer">${esc(q.answer)}</p></details><div class="notes"><span class="badge ${remaining?'remaining':''}">${badge}</span>${n?`<details><summary>Original question and automatic review</summary><blockquote>${esc(n.original_question)}</blockquote><p><b>Detected before review</b></p><ul>${flagText(n.flags_before)}</ul>${remaining?`<p><b>Still detected after review</b></p><ul>${flagText(n.flags_after)}</ul>`:'<p class="muted">No remaining lexical match detected.</p>'}<p class="muted">${esc(n.correction_status)}</p>${n.quality_repair_note?`<p><b>Additional quality review:</b> ${esc(n.quality_repair_note)}</p>`:''}</details>`:''}</div><details class="context" data-topic="${esc(q.study_topic_id)}"><summary>Complete supplied topic context</summary><pre>Expand to load context.</pre></details></article>`}).join('');
 for(const d of document.querySelectorAll('details.context'))d.addEventListener('toggle',async()=>{if(!d.open)return;let id=d.dataset.topic;try{if(!contextCache.has(id)){let r=await fetch('supplied-context/'+encodeURIComponent(id)+'.txt');if(!r.ok)throw Error('Context unavailable');contextCache.set(id,await r.text())}d.querySelector('pre').textContent=contextCache.get(id)}catch(e){d.querySelector('pre').textContent=e.message}})}
function filter(){const text=$('search').value.toLowerCase(),cat=$('category').value,status=$('status').value;filtered=questions.filter(q=>{const n=notes.get(q.question_id);return (!cat||q.category===cat)&&(!text||[q.topic,q.question,q.answer].join(' ').toLowerCase().includes(text))&&(!status||(status==='changed'&&n?.changed)||(status==='reviewed'&&n)||(status==='remaining'&&n?.flags_after?.length)||(status==='untouched'&&!n))});page=0;render()}
async function summary(){const r=await fetch('summary.json',{cache:'no-store'});if(!r.ok)throw Error('Summary unavailable');const s=await r.json();$('stats').innerHTML=`<div><b>${s.completed_topics.toLocaleString()} / ${s.target_topics.toLocaleString()}</b>topics complete</div><div><b>${s.generated_questions.toLocaleString()}</b>questions generated</div><div><b>${s.changed_questions.toLocaleString()}</b>questions corrected</div><div><b>$${(s.totals.estimated_usd||0).toFixed(4)}</b>new API cost estimate</div>`;$('runStatus').textContent=s.running?`Generation is running with ${s.active_topics} active topics. This page currently displays a saved snapshot of ${questions.length.toLocaleString()} questions; refresh after export completes.`:`${s.completed_topics===s.target_topics && s.failed_topics===0?'Generation complete.':'Generation stopped.'} ${s.failed_topics} failed topics; ${s.flagged_questions_after} questions retain detector flags. Updated ${s.updated_at}.`;return s}
async function start(){const responses=await Promise.all([fetch('typed-questions.json'),fetch('giveaway-review.json')]);if(responses.some(r=>!r.ok))throw Error('Question exports are not available yet');[questions,review]=await Promise.all(responses.map(r=>r.json()));notes=new Map(review.map(r=>[r.question_id,r]));for(const c of [...new Set(questions.map(q=>q.category))].sort()){$('category').add(new Option(c,c))}await summary();filter()}
for(const id of ['search','category','status'])$(id).addEventListener('input',filter);
$('previous').onclick=()=>{page--;render();window.scrollTo({top:0})};$('next').onclick=()=>{page++;render();window.scrollTo({top:0})};$('answers').onclick=()=>{showAnswers=!showAnswers;$('answers').textContent=showAnswers?'Hide answers':'Show answers';for(const d of document.querySelectorAll('.answerBox'))d.open=showAnswers};$('topics').onclick=()=>{$('topics').textContent=document.body.classList.toggle('hide-topics')?'Show topic labels':'Hide topic labels'};
start().catch(e=>{$('runStatus').textContent=e.message});setInterval(()=>summary().catch(()=>{}),15000);
</script></html>'''


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--run-dir',type=Path,default=RUN)
    args=parser.parse_args();(args.run_dir/'review.html').write_text(HTML)
    print(args.run_dir/'review.html')


if __name__=='__main__':main()
